# Generated by Django 2.2.28 on 2022-04-21 07:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220421_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 21, 10, 52, 49, 373966), verbose_name='Опубликована'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='posted',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 21, 10, 52, 49, 374963), verbose_name='Time published'),
        ),
    ]
